
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: stg_Name1
      description: "stg dbt model"
      columns:
          - name: ID
            description: Unique ID for each customer
            tests:
              - not_null:
                  config:
                    severity: error
          - name: FIRST_NAME
            description: first name for each customer
            tests:
              - not_null:
                  config:
                    severity: error
          - name: LAST_NAME
            description: last name for each customer
            tests:
              - not_null:
                  config:
                    severity: error
 